version: "3.7"
 
services:
  jenkins:
    user: root
    image: "jenkins/jenkins"
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /Users/kduque/Desktop/KarenGit/CI:/var/jenkins_home
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock